import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import queryString from 'query-string';
import { useSession } from '../context/session/SessionContext';
import { useEffect, useLayoutEffect, useState } from 'react';

export default function Home() {
  const [isLoggedIn, setIsLoggedIn] = useState()
  const [params, setParams] = useState({})
  const { state: sessionState } = useSession()

  const getUser = async () => {
    console.log(sessionState.access_token)
    try {
      const res = await fetch('https://api.spotify.com/v1/me/top/artists', {
        headers: {
          'Authorization': `Bearer ${sessionState.access_token}`,
          'content-type': "application/json"
        },
      })

      const data = await res.json();

      console.log({ data })
    } catch (error) {
      console.error("ERROR >>>", error)
    }
  }


  useLayoutEffect(() => {
    setIsLoggedIn(Boolean(sessionState.state && sessionState.access_token))

    if (!sessionState.state) {
      setParams({
        response_type: 'token',
        client_id: 'cc9a51f454504ac180a38007e56b0468',
        scope: 'user-read-private user-read-email user-top-read',
        state: Math.random().toString(20).substr(2, 14),
        redirect_uri: "http://localhost:3000/callback"
      })
    }

    getUser()
  }, [sessionState.state, sessionState.access_token])



  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello world</h1>
        <div>
          {
            typeof window !== 'undefined' && isLoggedIn ? (
              <p>You are logged in!</p>
            ) : (
              <>
                <h2>Get Started</h2>
                <p>Login Below to get started</p>
                <Link href={`https://accounts.spotify.com/authorize?${queryString.stringify(params)}`}>Login</Link>
              </>
            )
          }
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
